sources:
    nextzen-terrain:
        type: Raster
        url: https://tile.nextzen.org/tilezen/terrain/v1/256/normal/{z}/{x}/{y}.png
        url_params:
          api_key: '_Ynn_ixBRNaLmtWNwIIO3w'
        max_zoom: 14        
    nextzen:
        type: MVT
        url: https://tile.nextzen.org/tilezen/vector/v1/512/all/{z}/{x}/{y}.mvt
        url_params:
          api_key: '_Ynn_ixBRNaLmtWNwIIO3w'
        tile_size: 512
        max_zoom: 16
